services:
  portfolio_site_be:
    container_name: portfolio_site_be
    restart: "no"
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: runtime

  portfolio_site_be_migrator:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: migrator
