export type UserSuccessMessageKey =
  | "USER_CREATED_SUCCESS"
  | "USER_UPDATED_SUCCESS"
  | "USER_STATUS_UPDATED_SUCCESS"
  | "USER_DELETED_SUCCESS";

export type CertificationSuccessMessageKey =
  | "CERTIFICATION_CREATED_SUCCESS"
  | "CERTIFICATION_UPDATED_SUCCESS"
  | "CERTIFICATION_DELETED_SUCCESS"
  | "CERTIFICATION_SORT_UPDATED_SUCCESS";

export type EducationSuccessMessageKey =
  | "EDUCATION_CREATED_SUCCESS"
  | "EDUCATION_UPDATED_SUCCESS"
  | "EDUCATION_DELETED_SUCCESS"
  | "EDUCATION_SORT_UPDATED_SUCCESS";

export type ExperienceSuccessMessageKey =
  | "EXPERIENCE_CREATED_SUCCESS"
  | "EXPERIENCE_UPDATED_SUCCESS"
  | "EXPERIENCE_DELETED_SUCCESS"
  | "EXPERIENCE_SORT_UPDATED_SUCCESS";

export type SkillSuccessMessageKey =
  | "SKILL_CREATED_SUCCESS"
  | "SKILL_UPDATED_SUCCESS"
  | "SKILL_DELETED_SUCCESS"
  | "SKILL_SORT_UPDATED_SUCCESS";

export type SiteConfigSuccessMessageKey = "SITE_CONFIG_BULK_UPDATED_SUCCESS";
